# Generated by Django 5.1 on 2024-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeName', models.CharField(max_length=50)),
                ('shirtName', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeName', models.CharField(max_length=50)),
                ('shortName', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=50)),
                ('president', models.CharField(max_length=50)),
                ('foundationYear', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
