# Generated by Django 5.1 on 2024-08-29 19:01

import SportTeamApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Produto')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeName', models.CharField(max_length=50, unique=True, verbose_name='Nome Completo')),
                ('shirtName', models.CharField(max_length=20, verbose_name='Nome da Camisa')),
                ('birthDate', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('availability', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=3, verbose_name='Disponível')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], default='FW', max_length=2, verbose_name='Posição')),
                ('pos_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição da posição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeName', models.CharField(max_length=50, unique=True, verbose_name='Nome Completo')),
                ('shortName', models.CharField(max_length=20, verbose_name='Sigla ou Abreviação')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('stadium', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estádio/Ginásio')),
                ('coach', models.CharField(blank=True, max_length=50, null=True, verbose_name='Treinador')),
                ('president', models.CharField(blank=True, max_length=50, null=True, verbose_name='Presidente')),
                ('foundationYear', models.DateField(blank=True, null=True, verbose_name='Ano de Fundação')),
                ('shield', models.ImageField(blank=True, null=True, upload_to='shields/', verbose_name='Escudo')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
                ('completeDescription', models.TextField(max_length=200, verbose_name='Descrição Completa')),
                ('dateRecovey', models.DateField(verbose_name='Data de Recuperação')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportTeamApp.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, default=SportTeamApp.models.get_default_team, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='SportTeamApp.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('localGoals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('visitorGoals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='local', to='SportTeamApp.team')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visitor', to='SportTeamApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeName', models.CharField(max_length=70)),
                ('shortName', models.CharField(max_length=30)),
                ('serie', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=50)),
                ('type', models.CharField(choices=[('League', 'League'), ('Cup', 'Cup'), ('Friendly', 'Friendly')], default='League', max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('matches', models.ManyToManyField(to='SportTeamApp.match')),
                ('teams', models.ManyToManyField(to='SportTeamApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('local', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('players', models.ManyToManyField(related_name='trainings', to='SportTeamApp.player')),
            ],
        ),
    ]
