# Generated by Django 5.1 on 2024-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportTeamApp', '0002_team_acronym_alter_team_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthDate',
            field=models.DateField(verbose_name='Data de Nascimento (dd/mm/aaaa)'),
        ),
    ]
