package View;

import Controller.MenuController;

/**
 *
 * @author abraa
 */
public class MenuView extends javax.swing.JFrame {

    private final MenuController controller;
    
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        controller = new MenuController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MyTeamMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        TeamsMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        AddPlayerMenuItem = new javax.swing.JMenuItem();
        DelPlayerMenuItem = new javax.swing.JMenuItem();
        EditPlayerMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        TeamPerformanceMI = new javax.swing.JMenuItem();
        PlayerMenu = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        MaCMenu = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        MaSMenu = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jLabel4.setFont(new java.awt.Font("JimThorpe", 0, 48)); // NOI18N
        jLabel4.setText("My");

        jLabel5.setFont(new java.awt.Font("JimThorpe", 0, 48)); // NOI18N
        jLabel5.setText("Team");

        jLabel6.setFont(new java.awt.Font("JimThorpe", 0, 48)); // NOI18N
        jLabel6.setText("Management");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("JimThorpe", 0, 48)); // NOI18N
        jLabel7.setText("My");

        jLabel8.setFont(new java.awt.Font("JimThorpe", 0, 48)); // NOI18N
        jLabel8.setText("Team");

        jLabel9.setFont(new java.awt.Font("JimThorpe", 0, 48)); // NOI18N
        jLabel9.setText("Management");

        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(697, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );

        MyTeamMenu.setText("My Team");
        MyTeamMenu.setBorderPainted(false);
        MyTeamMenu.add(jMenuItem4);

        jMenuBar1.add(MyTeamMenu);

        TeamsMenu.setText("Teams");

        jMenu1.setText("Management");

        AddPlayerMenuItem.setText("Add");
        AddPlayerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlayerMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(AddPlayerMenuItem);

        DelPlayerMenuItem.setText("Delete");
        DelPlayerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelPlayerMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(DelPlayerMenuItem);

        EditPlayerMenuItem.setText("Edit");
        EditPlayerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPlayerMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(EditPlayerMenuItem);

        TeamsMenu.add(jMenu1);

        jMenuItem2.setText("List Teams");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        TeamsMenu.add(jMenuItem2);

        TeamPerformanceMI.setText("Performance");
        TeamPerformanceMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamPerformanceMIActionPerformed(evt);
            }
        });
        TeamsMenu.add(TeamPerformanceMI);

        jMenuBar1.add(TeamsMenu);

        PlayerMenu.setText("Players");

        jMenu5.setText("Management");

        jMenuItem8.setText("Add");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Delete");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Edit");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        PlayerMenu.add(jMenu5);

        jMenuItem6.setText("List Players");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        PlayerMenu.add(jMenuItem6);

        jMenuItem11.setText("Performance");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        PlayerMenu.add(jMenuItem11);

        jMenuBar1.add(PlayerMenu);

        MaCMenu.setText("Matches and Championchips");

        jMenu7.setText("Scheduling");

        jMenuItem14.setText("Single Match");
        jMenu7.add(jMenuItem14);

        jMenuItem15.setText("Tournments");
        jMenu7.add(jMenuItem15);

        MaCMenu.add(jMenu7);

        jMenuItem16.setText("jMenuItem16");
        MaCMenu.add(jMenuItem16);

        jMenuBar1.add(MaCMenu);

        MaSMenu.setText("Metrics and Stats");
        jMenuBar1.add(MaSMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void EditPlayerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPlayerMenuItemActionPerformed
        //Edit Team  
    }//GEN-LAST:event_EditPlayerMenuItemActionPerformed

    private void AddPlayerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlayerMenuItemActionPerformed
       //Add Team
       AddTeamView addTeamView = new AddTeamView();
       jDesktopPane1.add(addTeamView);
       addTeamView.setVisible(true);       
    }//GEN-LAST:event_AddPlayerMenuItemActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        //Add Player
        AddPlayerView addPlayerView = new AddPlayerView();
        jDesktopPane1.add(addPlayerView);
        addPlayerView.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        //Edit Player        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void TeamPerformanceMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamPerformanceMIActionPerformed
        //Team Performance
    }//GEN-LAST:event_TeamPerformanceMIActionPerformed

    private void DelPlayerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelPlayerMenuItemActionPerformed
        //Delete Team     
    }//GEN-LAST:event_DelPlayerMenuItemActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //Delete Player       
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //List Teams
                
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        //Player Performance
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddPlayerMenuItem;
    private javax.swing.JMenuItem DelPlayerMenuItem;
    private javax.swing.JMenuItem EditPlayerMenuItem;
    private javax.swing.JMenu MaCMenu;
    private javax.swing.JMenu MaSMenu;
    private javax.swing.JMenu MyTeamMenu;
    private javax.swing.JMenu PlayerMenu;
    private javax.swing.JMenuItem TeamPerformanceMI;
    private javax.swing.JMenu TeamsMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
